---
title: "Further Readings"
---


##Books 

*Applications of Information Theory to Epidemiology* by Dr. Gareth Hughes, https://apsjournals.apsnet.org/doi/book/10.1094/9780890544877



##Papers (in no particular order)

McRoberts, N., Hall, C., Madden, L. V., & Hughes, G. (2011). Perceptions of disease risk: from social construction of subjective judgments to rational decision making. Phytopathology, 101(6), 654-665.

Hughes, G., & McRoberts, N. (2014). The structure of diagnostic information. Australasian Plant Pathology, 43(3), 267-286.

Gent, D. H., Mahaffee, W. F., McRoberts, N., & Pfender, W. F. (2013). The use and role of predictive systems in disease management. Annual review of phytopathology, 51, 267-289.

Newton, A. C., McRoberts, N., & Hughes, G. (2006). Information technology in plant disease epidemiology. In The Epidemiology of Plant Diseases (pp. 335-356). Springer, Dordrecht.

Hughes, G., McRoberts, N., & Burnett, F. J. (2015). Information graphs for binary predictors. Phytopathology, 105(1), 9-17.

Hughes, G., & Burnett, F. J. (2017). Evaluation of probabilistic disease forecasts. Phytopathology, 107(10), 1136-1143.

Yuen, J. E., & Hughes, G. (2002). Bayesian analysis of plant disease prediction. Plant Pathology, 51(4), 407-412.

Hughes, G. (2017). The evidential basis of decision making in plant disease management. Annual review of phytopathology, 55, 41-59.


