---
title: "Welcome!"
---

##Information Theory ICPP 2018 Workshop

### Welcome!
 
The workshop will take place on 2018-07-29 from 8am-12pm at the Hynes Convention Center Room 203.

You will need to download R (https://www.r-project.org/) and we will be using RStudio, which is an Integrated Development Environment for R, which you can find at https://www.rstudio.com/products/rstudio/download/. The free version should be good enough to do what you want.

You will also need to download some packages for R. Enter into your R console:

>install.packages("tidyverse", "broom", "DescTools", "philentropy", "infotheo")

These packages all do different things: *tidyverse* and *broom* are useful for cleaning up data, *DescTools* is useful for descriptive statistics, and *philentropy* and *infotheo* are useful for calculating information theory metrics. 

### Prerequisites

General knowledge of agricultural, ecological, or epidemiological systems

### Contacts

####Instructor: 

Dr. Neil McRoberts 
Plant Pathology Department
University of California, Davis
Email: n m c r o b e r t s at uc davis dot edu


####Teaching Assistant: 

Dr. Robin Choudhury
Department of Plant Pathology
University of Florida
Email: r a dot c h o u d h u r y at u f l dot edu

### Workshop overview

The use of information theoretic quantities to explain recipients' differential responses to decision support outputs was first proposed by McRoberts et al at the ICPP in Christchurch in 2003. In the intervening 15 years a set of information theoretic concepts for epidemiologists, diagnosticians, and decision-makers has been developed and summarized in a book by Hughes and several papers by Hughes, McRoberts and others. The workshop will combine lectures on concepts with practical computer exercises to allow participants to learn to calculate key information quantities that are important in understanding how DSS's and diagnostics work, fundamentally, by capturing information from the world and making it available for use in decision-making. Workshop materials will be prepared by McRoberts and Hughes and taught by McRoberts. All material will be available to participants to keep.

### Course learning objectives

Participants who have completed this course will be able to…

+	broadly understand information theory in the context of plant disease epidemiology

+	understand the uses of different metrics for how to assess the information of your system

+	analyze basic information theory problems using R
